export const GET_SUBCRIPTION_BEGIN = "GET_SUBCRIPTION_BEGIN";
export const POST_OTP_LOGIN_BEGIN = "POST_OTP_LOGIN_BEGIN";
export const POST_OTP_LOGIN_SUCCESS = "POST_OTP_LOGIN_SUCCESS";
export const BUYSUBSCRIPTION_BEGIN = "BUYSUBSCRIPTION_BEGIN";

export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";

export const GETDATA_BEGIN = "GETDATA_BEGIN";
export const GETDATA_SUCCESS = "GETDATA_SUCCESS";
export const GETDATA_ERROR = "GETDATA_ERROR";

export const SET_AGREE = "SET_AGREE";

export const GET_EACHDOCTOR_PATIENT_BEGIN = "GET_EACHDOCTOR_PATIENT_SUCCESS";
export const GET_EACHDOCTOR_PATIENT_SUCCESS = "GET_EACHDOCTOR_PATIENT_SUCCESS";

export const GET_TEST_REPORTS_BEGIN = "GET_TEST_REPORTS_BEGIN";
export const GET_TEST_REPORTS_SUCCESS = "GET_TEST_REPORTS_SUCCESS";

export const GET_ARRAY_OF_OBJECT_BEGIN = "GET_ARRAY_OF_OBJECT_BEGIN";
export const GET_ARRAY_OF_OBJECT_SUCCESS = "GET_ARRAY_OF_OBJECT_SUCCESS";
export const GET_ARRAY_OF_OBJECT_ERROR = "GET_ARRAY_OF_OBJECT_ERROR";

export const GET_ADMIN_HOME_BEGIN = "GET_ADMIN_HOME_BEGIN";
export const GET_ADMIN_HOME_SUCCESS = "GET_ADMIN_HOME_SUCCESS";
export const GET_ADMIN_HOME_ERROR = "GET_ADMIN_HOME_ERROR";

export const SET_QUERY_ID = "SET_QUERY_ID";

export const GET_COMMON_DATA_BEGIN = "GET_COMMON_DATA_BEGIN";
export const GET_COMMON_DATA_SUCCESS = "GET_COMMON_DATA_SUCCESS";
export const GET_COMMON_DATA_ERROR = "GET_COMMON_DATA_ERROR";

//
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_NUTRITION_SUCESS = "GET_NUTRITION_SUCESS";
export const GET_DOCTOR_ID_BEGIN = "GET_DOCTOR_ID_BEGIN";
export const GET_DOCTOR_ID_SUCCESS = "GET_DOCTOR_ID_SUCCESS";
